import { renderTechstackList } from "@/helpers/renderTechstack";

export const blogPostsData = [
  {
    id: 1,
    responsible: [
      'Converting interface from Figma File to ReactJS',
      'Creating responsive interface for all devices',
      'Handling features and interactions on the website',
      "Integrating APIs from Back-End",
    ],
    title: 'PleaseSpeak (BinhMinh Group)',
    desc: '(Based on Duolingo) Software to support teaching, searching for documents, question banks and English test preparation for both teachers & students, integrating AI.',
    source: 'private',
    live: 'https://pleasespeak.vn',
    imageUrl: './project1Preview.png',
    logoUrl: '/project1.png',
    data: renderTechstackList(['react', 'typeScript', 'vite', 'shadcn', 'tailwind', 'redux', 'zustand', 'antd' ,'framermotion', 'reacthookform', 'socketio']),
  },
  {
    id: 3,
    responsible: [
      'Developing and maintaining responsive web applications, ensuring smooth UI/UX design.',
      'Contributing to backend development by implementing RESTful APIs.',
      'Conducting system analysis and design, including requirements gathering and analysis.',
    ],
    title: 'LamanClinic',
    desc: 'A Management Support System for Multi-Specialty Clinics.',
    source: 'https://github.com/kidiezyllex/KLTN_FE',
    live: 'https://lamanclinic.vercel.app/',
    imageUrl: 'https://res.cloudinary.com/drqbhj6ft/image/upload/v1736393133/learning-webdev-blog/portfolio/laman_cpuvcr.png',
    logoUrl: 'https://res.cloudinary.com/drqbhj6ft/image/upload/v1736248592/learning-webdev-blog/portfolio/2_tifbwx.jpg',
    data: renderTechstackList(['nextjs', 'typeScript', 'shadcn', 'tailwind', 'Clerk', 'nextauth', 'zustand', 'uploadthing', 'nodejs', 'expressjs', 'mongodb', 'redis', 'apachekafka']),
  },
  {
    id: 4,
    responsible: [
      'Build the online sports website interface according to the original page.',
      'Set-up UI/UX libraries, build common components and handle responsive interface errors.',
      'Handle Api Client and CMS Api.',
      'Participate in producing the missing Api for Back-End.',
    ],
    title: 'Luscsenger',
    desc: 'A Real-time Calling & Texting Application.',
    source: 'https://github.com/kidiezyllex/messenger-clone',
    live: 'https://luscsenger.vercel.app/',
    imageUrl: 'https://res.cloudinary.com/drqbhj6ft/image/upload/v1736393133/learning-webdev-blog/portfolio/luscenger_qbu2kf.png',
    logoUrl: 'https://res.cloudinary.com/drqbhj6ft/image/upload/v1736248592/learning-webdev-blog/portfolio/3_huctrt.jpg',
    data: renderTechstackList(['nextjs', 'typeScript', 'shadcn', 'tailwind', 'nextauth', 'zustand', 'uploadthing', 'nodejs', 'expressjs', 'postgresql', 'prisma', 'pusher', 'zegocloud', 'yetanotherreactlightbox']),
  },
  {
    id: 5,
    responsible: [
      'Build the online sports website interface according to the original page.',
      'Set-up UI/UX libraries, build common components and handle responsive interface errors.',
      'Handle Api Client and CMS Api.',
      'Participate in producing the missing Api for Back-End.',
    ],
    title: 'Proma',
    desc: 'A Project Management Application.',
    source: 'https://github.com/kidiezyllex/project-management',
    live: '/',
    imageUrl: 'https://studio.uxpincdn.com/studio/wp-content/uploads/2022/08/Zrzut-ekranu-2022-08-26-o-14.10.43-1024x589.png.webp',
    logoUrl: 'https://res.cloudinary.com/drqbhj6ft/image/upload/v1736248593/learning-webdev-blog/portfolio/1_isev00.jpg',
    data: renderTechstackList(['nextjs', 'typeScript', 'shadcn', 'tailwind', 'nextauth', 'zustand', 'uploadthing', 'nodejs', 'expressjs', 'postgresql', 'prisma', 'pusher', 'zegocloud', 'yetanotherreactlightbox']),
  },
];

export const blogPostsDataVN = [
  {
    id: 1,
    responsible: [
      'Cắt giao diện từ Figma File sang ReactJS',
      'Tạo giao diện đảm bảo responsive cho tất cả các thiết bị',
      'Xử lý các tính năng, tương tác trên trang web',
      "Ghép nối các API từ Back-End",
    ],
    title: 'PleaseSpeak (BinhMinh Group)',
    desc: '(Dựa trên Duolingo) Phần mềm hỗ trợ giảng dạy, tìm kiếm tài liệu, ngân hàng câu hỏi và luyện thi tiếng Anh cho cả giáo viên & học sinh, tích hợp AI.',
    source: 'private',
    live: 'https://pleasespeak.vn',
    imageUrl: './project1Preview.png',
    logoUrl: '/project1.png',
    data: renderTechstackList(['nextjs', 'typeScript', 'shadcn', 'tailwind', 'redux', 'framermotion', 'reacthookform', 'socketio']),
  },
  {
    id: 3,
    responsible: [
      'Phát triển và duy trì các ứng dụng web đáp ứng, đảm bảo thiết kế UI/UX mượt mà.',
      'Đóng góp vào phát triển backend bằng cách triển khai các API RESTful.',
      'Tiến hành phân tích và thiết kế hệ thống, bao gồm thu thập và phân tích yêu cầu.',
    ],
    title: 'LamanClinic',
    desc: 'Hệ thống hỗ trợ quản lý cho các phòng khám đa chuyên khoa.',
    source: 'https://github.com/kidiezyllex/KLTN_FE',
    live: 'https://lamanclinic.vercel.app/',
    imageUrl: 'https://res.cloudinary.com/drqbhj6ft/image/upload/v1736393133/learning-webdev-blog/portfolio/laman_cpuvcr.png',
    logoUrl: 'https://res.cloudinary.com/drqbhj6ft/image/upload/v1736248592/learning-webdev-blog/portfolio/2_tifbwx.jpg',
    data: renderTechstackList(['nextjs', 'typeScript', 'shadcn', 'tailwind', 'Clerk', 'nextauth', 'zustand', 'uploadthing', 'nodejs', 'expressjs', 'mongodb', 'redis', 'apachekafka']),
  },
  {
    id: 4,
    responsible: [
      'Xây dựng giao diện trang web thể thao trực tuyến theo trang gốc.',
      'Thiết lập thư viện UI/UX, xây dựng các component chung và xử lý lỗi giao diện responsive.',
      'Xử lý Api Client và CMS Api.',
      'Tham gia sản xuất các Api còn thiếu cho Back-End.',
    ],
    title: 'Luscsenger',
    desc: 'Ứng dụng gọi điện & nhắn tin thời gian thực.',
    source: 'https://github.com/kidiezyllex/messenger-clone',
    live: 'https://luscsenger.vercel.app/',
    imageUrl: 'https://res.cloudinary.com/drqbhj6ft/image/upload/v1736393133/learning-webdev-blog/portfolio/luscenger_qbu2kf.png',
    logoUrl: 'https://res.cloudinary.com/drqbhj6ft/image/upload/v1736248592/learning-webdev-blog/portfolio/3_huctrt.jpg',
    data: renderTechstackList(['nextjs', 'typeScript', 'shadcn', 'tailwind', 'nextauth', 'zustand', 'uploadthing', 'nodejs', 'expressjs', 'postgresql', 'prisma', 'pusher', 'zegocloud', 'yetanotherreactlightbox']),
  },
  {
    id: 5,
    responsible: [
      'Xây dựng giao diện trang web thể thao trực tuyến theo trang gốc.',
      'Thiết lập thư viện UI/UX, xây dựng các component chung và xử lý lỗi giao diện responsive.',
      'Xử lý Api Client và CMS Api.',
      'Tham gia sản xuất các Api còn thiếu cho Back-End.',
    ],
    title: 'Proma',
    desc: 'Ứng dụng quản lý dự án.',
    source: 'https://github.com/kidiezyllex/project-management',
    live: '/',
    imageUrl: 'https://studio.uxpincdn.com/studio/wp-content/uploads/2022/08/Zrzut-ekranu-2022-08-26-o-14.10.43-1024x589.png.webp',
    logoUrl: 'https://res.cloudinary.com/drqbhj6ft/image/upload/v1736248593/learning-webdev-blog/portfolio/1_isev00.jpg',
    data: renderTechstackList(['nextjs', 'typeScript', 'shadcn', 'tailwind', 'nextauth', 'zustand', 'uploadthing', 'nodejs', 'expressjs', 'postgresql', 'prisma', 'pusher', 'zegocloud', 'yetanotherreactlightbox']),
  },
];
